// <auto-generated />
using System;
using Adnd.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Adnd.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802034712_AddLlmInteractionLogStatus")]
    partial class AddLlmInteractionLogStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adnd.Server.Models.AgentCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("FromAgent")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Input")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<string>("OutputMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCallId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("ToAgent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentCallId");

                    b.HasIndex("GameId", "Status", "CreatedAt");

                    b.ToTable("AgentCalls");
                });

            modelBuilder.Entity("Adnd.Server.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Adnd.Server.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Background")
                        .HasColumnType("text");

                    b.Property<string>("BackgroundFeatures")
                        .HasColumnType("text");

                    b.Property<string>("BackgroundProficiencies")
                        .HasColumnType("text");

                    b.Property<string>("BackgroundSkills")
                        .HasColumnType("text");

                    b.Property<string>("Backstory")
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer");

                    b.Property<string>("CustomFields")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Inventory")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SpellAttackBonus")
                        .HasColumnType("integer");

                    b.Property<int>("SpellSaveDC")
                        .HasColumnType("integer");

                    b.Property<string>("SpellSlots")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SpellcastingAbility")
                        .HasColumnType("text");

                    b.Property<string>("Spells")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Adnd.Server.Models.Combat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentTurnIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<float>("InitiativeCount")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Combats");
                });

            modelBuilder.Entity("Adnd.Server.Models.CombatEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CombatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Turn")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CombatId");

                    b.ToTable("CombatEvents");
                });

            modelBuilder.Entity("Adnd.Server.Models.CombatParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AC")
                        .HasColumnType("integer");

                    b.Property<int>("ActionsRemaining")
                        .HasColumnType("integer");

                    b.Property<int>("BonusActionsRemaining")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CombatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DeathSaveState")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FreeActions")
                        .HasColumnType("integer");

                    b.Property<int>("HP")
                        .HasColumnType("integer");

                    b.Property<float>("Initiative")
                        .HasColumnType("real");

                    b.Property<float>("InitiativeCount")
                        .HasColumnType("real");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<int>("MovementsRemaining")
                        .HasColumnType("integer");

                    b.Property<Guid?>("NPCId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticipantType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReactionsRemaining")
                        .HasColumnType("integer");

                    b.Property<string>("SavingThrows")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TemporaryHP")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CombatId");

                    b.ToTable("CombatParticipants");
                });

            modelBuilder.Entity("Adnd.Server.Models.CustomSystemDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("CustomSystems");
                });

            modelBuilder.Entity("Adnd.Server.Models.EventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("GameId", "Status");

                    b.ToTable("EventRecords");
                });

            modelBuilder.Entity("Adnd.Server.Models.GMToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentCallId")
                        .HasColumnType("uuid");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresConfirmation")
                        .HasColumnType("boolean");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ToolIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GMToolCalls");
                });

            modelBuilder.Entity("Adnd.Server.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomSystemJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GMStatus")
                        .HasColumnType("integer");

                    b.Property<string>("GameParameters")
                        .HasColumnType("text");

                    b.Property<string>("GameState")
                        .HasColumnType("text");

                    b.Property<string>("InviteCode")
                        .HasColumnType("text")
                        .HasColumnName("invitecode");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LLMPresetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastGMAction")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastGMActionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlotSeed")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemVersion")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("CurrentSessionId")
                        .IsUnique();

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasFilter("\"invitecode\" IS NOT NULL");

                    b.HasIndex("LLMPresetId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GameParameters")
                        .HasColumnType("text");

                    b.Property<Guid?>("LLMPresetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlotSeed")
                        .HasColumnType("text");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameTemplates");
                });

            modelBuilder.Entity("Adnd.Server.Models.LLMInteractionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginGameId")
                        .HasColumnType("uuid");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OriginGameId", "StartedAt");

                    b.ToTable("LLMInteractionLogs");
                });

            modelBuilder.Entity("Adnd.Server.Models.LLMPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("BaseModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingEndpointUrl")
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text");

                    b.Property<string>("EndpointUrl")
                        .HasColumnType("text");

                    b.Property<string>("ExtraParams")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("FrequencyPenalty")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PresencePenalty")
                        .HasColumnType("real");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasoningEffort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Stream")
                        .HasColumnType("boolean");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<int?>("TimeoutMs")
                        .HasColumnType("integer");

                    b.Property<float>("TopP")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("LLMPresets");
                });

            modelBuilder.Entity("Adnd.Server.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOOC")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WhisperFromId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhisperTarget")
                        .HasColumnType("text");

                    b.Property<Guid?>("WhisperToId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Adnd.Server.Models.NPC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attitude")
                        .HasColumnType("integer");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Faction")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Inventory")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("NPCs");
                });

            modelBuilder.Entity("Adnd.Server.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Updates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PlotReviews");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdaptationHistory")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector");

                    b.Property<string>("Foreshadowing")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyEventMessageIds")
                        .HasColumnType("text");

                    b.Property<string>("MilestoneEvents")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("Momentum")
                        .HasColumnType("real");

                    b.Property<string>("NextMilestone")
                        .HasColumnType("text");

                    b.Property<float>("RelevanceScore")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PlotThreads");
                });

            modelBuilder.Entity("Adnd.Server.Models.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PromptTemplates");
                });

            modelBuilder.Entity("Adnd.Server.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Adnd.Server.Models.SessionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("SessionNotes");
                });

            modelBuilder.Entity("Adnd.Server.Models.ToolCallCoordinator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentCallId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedTools")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentToolIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ToolCalls")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ToolResults")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TotalTools")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentCallId");

                    b.ToTable("ToolCallCoordinators");
                });

            modelBuilder.Entity("Adnd.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Adnd.Server.Models.Whisper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FromPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetPlayerIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Whispers");
                });

            modelBuilder.Entity("Adnd.Server.Models.AgentCall", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", null)
                        .WithMany("AgentCalls")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.AgentCall", "ParentCall")
                        .WithMany("ChildCalls")
                        .HasForeignKey("ParentCallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCall");
                });

            modelBuilder.Entity("Adnd.Server.Models.Character", b =>
                {
                    b.HasOne("Adnd.Server.Models.Player", "Player")
                        .WithOne("Character")
                        .HasForeignKey("Adnd.Server.Models.Character", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Adnd.Server.Models.CombatEvent", b =>
                {
                    b.HasOne("Adnd.Server.Models.Combat", "Combat")
                        .WithMany("Events")
                        .HasForeignKey("CombatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combat");
                });

            modelBuilder.Entity("Adnd.Server.Models.CombatParticipant", b =>
                {
                    b.HasOne("Adnd.Server.Models.Combat", "Combat")
                        .WithMany("Participants")
                        .HasForeignKey("CombatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combat");
                });

            modelBuilder.Entity("Adnd.Server.Models.CustomSystemDefinition", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.Game", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "Creator")
                        .WithMany("Games")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.GameSession", "CurrentSession")
                        .WithOne()
                        .HasForeignKey("Adnd.Server.Models.Game", "CurrentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Adnd.Server.Models.LLMPreset", "LLMPreset")
                        .WithMany("Games")
                        .HasForeignKey("LLMPresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("CurrentSession");

                    b.Navigation("LLMPreset");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameSession", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameTemplate", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.LLMInteractionLog", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.LLMPreset", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany("LLMPresets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.Message", b =>
                {
                    b.HasOne("Adnd.Server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Adnd.Server.Models.NPC", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("NPCs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.Player", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotReview", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("PlotReviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotThread", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("PlotThreads")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.RefreshToken", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.SessionNote", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.ToolCallCoordinator", b =>
                {
                    b.HasOne("Adnd.Server.Models.AgentCall", "AgentCall")
                        .WithMany()
                        .HasForeignKey("AgentCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentCall");
                });

            modelBuilder.Entity("Adnd.Server.Models.Whisper", b =>
                {
                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Adnd.Server.Models.AgentCall", b =>
                {
                    b.Navigation("ChildCalls");
                });

            modelBuilder.Entity("Adnd.Server.Models.Combat", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Adnd.Server.Models.Game", b =>
                {
                    b.Navigation("AgentCalls");

                    b.Navigation("NPCs");

                    b.Navigation("Players");

                    b.Navigation("PlotReviews");

                    b.Navigation("PlotThreads");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Adnd.Server.Models.LLMPreset", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Adnd.Server.Models.Player", b =>
                {
                    b.Navigation("Character");
                });

            modelBuilder.Entity("Adnd.Server.Models.User", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("LLMPresets");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
