// <auto-generated />
using System;
using Adnd.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Adnd.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607180000_PlotWeaverDynamicGeneration")]
    partial class PlotWeaverDynamicGeneration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Adnd.Server.Models.PlotReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Updates")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "ReviewedAt")
                        .IsDescending(false, true);

                    b.ToTable("PlotReviews");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Embedding")
                        .HasColumnType("vector");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("KeyEventMessageIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<float>("Momentum")
                        .HasColumnType("real");

                    b.Property<float>("RelevanceScore")
                        .HasColumnType("real");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("boolean");

                    b.Property<string>("MilestoneEvents")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PlotThreads");
                });

#pragma warning restore 612, 618
        }
    }
}
