// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Adnd.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Adnd.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612115626_SingleSessionPerGame")]
    partial class SingleSessionPerGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adnd.Server.Models.AgentCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("FromAgent")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Input")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<string>("OutputMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCallId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("ToAgent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCallId");

                    b.HasIndex("SessionId");

                    b.HasIndex("GameId", "Status", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("AgentCalls");
                });

            modelBuilder.Entity("Adnd.Server.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonElement>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<string>("Background")
                        .HasColumnType("text");

                    b.Property<JsonElement?>("BackgroundFeatures")
                        .HasColumnType("jsonb");

                    b.Property<JsonElement?>("BackgroundProficiencies")
                        .HasColumnType("jsonb");

                    b.Property<JsonElement?>("BackgroundSkills")
                        .HasColumnType("jsonb");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonElement>("Conditions")
                        .HasColumnType("jsonb");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer");

                    b.Property<JsonElement>("CustomFields")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonElement>("Inventory")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("integer");

                    b.Property<JsonElement>("Skills")
                        .HasColumnType("jsonb");

                    b.Property<int?>("SpellAttackBonus")
                        .HasColumnType("integer");

                    b.Property<int?>("SpellSaveDC")
                        .HasColumnType("integer");

                    b.Property<JsonElement?>("SpellSlots")
                        .HasColumnType("jsonb");

                    b.Property<JsonElement?>("SpellcastingAbility")
                        .HasColumnType("jsonb");

                    b.Property<JsonElement>("Spells")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Adnd.Server.Models.Combat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentTurnIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("InitiativeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<JsonElement?>("Notes")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("GameId", "Status");

                    b.ToTable("Combats");
                });

            modelBuilder.Entity("Adnd.Server.Models.CombatEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CombatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CombatId");

                    b.ToTable("CombatEvents");
                });

            modelBuilder.Entity("Adnd.Server.Models.CombatParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AC")
                        .HasColumnType("integer");

                    b.Property<int>("ActionsRemaining")
                        .HasColumnType("integer");

                    b.Property<int>("BonusActionsRemaining")
                        .HasColumnType("integer");

                    b.Property<Guid>("CombatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer");

                    b.Property<string>("DeathSaveState")
                        .HasColumnType("jsonb");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonElement?>("FreeActions")
                        .HasColumnType("jsonb");

                    b.Property<int>("Initiative")
                        .HasColumnType("integer");

                    b.Property<int?>("InitiativeBonus")
                        .HasColumnType("integer");

                    b.Property<int>("InitiativeCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<int>("MovementsRemaining")
                        .HasColumnType("integer");

                    b.Property<JsonElement?>("Notes")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("NpcId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReactionsRemaining")
                        .HasColumnType("integer");

                    b.Property<string>("SavingThrows")
                        .HasColumnType("jsonb");

                    b.Property<string>("TemporaryHP")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CombatId");

                    b.HasIndex("NpcId");

                    b.HasIndex("PlayerId");

                    b.ToTable("CombatParticipants");
                });

            modelBuilder.Entity("Adnd.Server.Models.CustomSystemDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("JsonDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("CustomSystems");
                });

            modelBuilder.Entity("Adnd.Server.Models.GMToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Arguments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfirmedByPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("ExpirationTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("OutputMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentToolCallId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresConfirmation")
                        .HasColumnType("boolean");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByPlayerId");

                    b.HasIndex("GameId");

                    b.HasIndex("ParentToolCallId");

                    b.HasIndex("SessionId");

                    b.ToTable("GMToolCalls");
                });

            modelBuilder.Entity("Adnd.Server.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomSystemJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GMStatus")
                        .HasColumnType("integer");

                    b.Property<string>("GameParameters")
                        .HasColumnType("text");

                    b.Property<string>("GameState")
                        .HasColumnType("text");

                    b.Property<string>("InviteCode")
                        .HasColumnType("text")
                        .HasColumnName("invitecode");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LLMPresetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastGMAction")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastGMActionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlotSeed")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemVersion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("CurrentSessionId")
                        .IsUnique();

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasFilter("invitecode IS NOT NULL");

                    b.HasIndex("LLMPresetId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameState")
                        .HasColumnType("text");

                    b.Property<string>("PlotNodes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultName")
                        .HasColumnType("text");

                    b.Property<string>("GameParameters")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LLMPresetId")
                        .HasColumnType("uuid");

                    b.Property<string>("LLMPresetName")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlotSeed")
                        .HasColumnType("text");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LLMPresetId");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("GameTemplates");
                });

            modelBuilder.Entity("Adnd.Server.Models.LLMInteractionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("EndpointUrl")
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginAction")
                        .HasColumnType("text");

                    b.Property<string>("OriginAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginGameId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("uuid");

                    b.Property<string>("PresetName")
                        .HasColumnType("text");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestJson")
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserPrompt")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("UserId", "OriginGameId", "StartedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("LLMInteractionLogs");
                });

            modelBuilder.Entity("Adnd.Server.Models.LLMPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("BaseModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingEndpointUrl")
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text");

                    b.Property<string>("EndpointUrl")
                        .HasColumnType("text");

                    b.Property<JsonElement?>("ExtraParams")
                        .HasColumnType("jsonb");

                    b.Property<float?>("FrequencyPenalty")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("PresencePenalty")
                        .HasColumnType("real");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Stream")
                        .HasColumnType("boolean");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<float>("TopP")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("LLMPresets");
                });

            modelBuilder.Entity("Adnd.Server.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOOC")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WhisperFromId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhisperTarget")
                        .HasColumnType("text");

                    b.Property<Guid?>("WhisperToId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("WhisperFromId");

                    b.HasIndex("WhisperToId");

                    b.HasIndex("SessionId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Adnd.Server.Models.NPC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonElement>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<JsonElement>("Inventory")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PlotThreadId")
                        .HasColumnType("uuid");

                    b.Property<JsonElement>("Skills")
                        .HasColumnType("jsonb");

                    b.Property<JsonElement>("Spells")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlotThreadId");

                    b.ToTable("NPCs");
                });

            modelBuilder.Entity("Adnd.Server.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanWhisper")
                        .HasColumnType("boolean");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("WhisperGroups")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Updates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "ReviewedAt")
                        .IsDescending(false, true);

                    b.ToTable("PlotReviews");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdaptationHistory")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector");

                    b.Property<string>("Foreshadowing")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<Guid>>("KeyEventMessageIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("MilestoneEvents")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("Momentum")
                        .HasColumnType("real");

                    b.Property<string>("NextMilestone")
                        .HasColumnType("text");

                    b.Property<float>("RelevanceScore")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Status");

                    b.HasIndex("GameId", "Title")
                        .HasDatabaseName("IX_PlotThreads_GameId_Title");

                    b.ToTable("PlotThreads");
                });

            modelBuilder.Entity("Adnd.Server.Models.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "Type", "Name")
                        .IsUnique();

                    b.ToTable("PromptTemplates");
                });

            modelBuilder.Entity("Adnd.Server.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Adnd.Server.Models.SessionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SessionId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("SessionNotes");
                });

            modelBuilder.Entity("Adnd.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Adnd.Server.Models.Whisper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("TargetPlayerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromPlayerId");

                    b.HasIndex("SessionId");

                    b.HasIndex("GameId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Whispers");
                });

            modelBuilder.Entity("Adnd.Server.Services.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Adnd.Server.Models.AgentCall", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("AgentCalls")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.AgentCall", "ParentCall")
                        .WithMany("ChildCalls")
                        .HasForeignKey("ParentCallId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Game");

                    b.Navigation("ParentCall");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Adnd.Server.Models.Character", b =>
                {
                    b.HasOne("Adnd.Server.Models.Player", "Player")
                        .WithOne("Character")
                        .HasForeignKey("Adnd.Server.Models.Character", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Adnd.Server.Models.Combat", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Game");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Adnd.Server.Models.CombatEvent", b =>
                {
                    b.HasOne("Adnd.Server.Models.Combat", "Combat")
                        .WithMany("Events")
                        .HasForeignKey("CombatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combat");
                });

            modelBuilder.Entity("Adnd.Server.Models.CombatParticipant", b =>
                {
                    b.HasOne("Adnd.Server.Models.Combat", "Combat")
                        .WithMany("Participants")
                        .HasForeignKey("CombatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.NPC", "NPC")
                        .WithMany()
                        .HasForeignKey("NpcId");

                    b.HasOne("Adnd.Server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Combat");

                    b.Navigation("NPC");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Adnd.Server.Models.CustomSystemDefinition", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.GMToolCall", b =>
                {
                    b.HasOne("Adnd.Server.Models.Player", "ConfirmedByPlayer")
                        .WithMany()
                        .HasForeignKey("ConfirmedByPlayerId");

                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.GMToolCall", "ParentToolCall")
                        .WithMany("ChildToolCalls")
                        .HasForeignKey("ParentToolCallId");

                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("ConfirmedByPlayer");

                    b.Navigation("Game");

                    b.Navigation("ParentToolCall");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Adnd.Server.Models.Game", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.GameSession", "CurrentSession")
                        .WithOne()
                        .HasForeignKey("Adnd.Server.Models.Game", "CurrentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Adnd.Server.Models.LLMPreset", "LLMPreset")
                        .WithMany()
                        .HasForeignKey("LLMPresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("CurrentSession");

                    b.Navigation("LLMPreset");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameSession", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameTemplate", b =>
                {
                    b.HasOne("Adnd.Server.Models.LLMPreset", "LLMPreset")
                        .WithMany()
                        .HasForeignKey("LLMPresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LLMPreset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.LLMInteractionLog", b =>
                {
                    b.HasOne("Adnd.Server.Models.LLMPreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.LLMPreset", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.Message", b =>
                {
                    b.HasOne("Adnd.Server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.Player", "WhisperFrom")
                        .WithMany()
                        .HasForeignKey("WhisperFromId");

                    b.HasOne("Adnd.Server.Models.Player", "WhisperTo")
                        .WithMany()
                        .HasForeignKey("WhisperToId");

                    b.Navigation("Player");

                    b.Navigation("Session");

                    b.Navigation("WhisperFrom");

                    b.Navigation("WhisperTo");
                });

            modelBuilder.Entity("Adnd.Server.Models.NPC", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("NPCs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.PlotThread", "PlotThread")
                        .WithMany()
                        .HasForeignKey("PlotThreadId");

                    b.Navigation("Game");

                    b.Navigation("PlotThread");
                });

            modelBuilder.Entity("Adnd.Server.Models.Player", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotReview", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("PlotReviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotThread", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("PlotThreads")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.PromptTemplate", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.RefreshToken", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.SessionNote", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Adnd.Server.Models.Whisper", b =>
                {
                    b.HasOne("Adnd.Server.Models.Player", "FromPlayer")
                        .WithMany()
                        .HasForeignKey("FromPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromPlayer");

                    b.Navigation("Game");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Adnd.Server.Services.AuditLog", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.AgentCall", b =>
                {
                    b.Navigation("ChildCalls");
                });

            modelBuilder.Entity("Adnd.Server.Models.Combat", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Adnd.Server.Models.GMToolCall", b =>
                {
                    b.Navigation("ChildToolCalls");
                });

            modelBuilder.Entity("Adnd.Server.Models.Game", b =>
                {
                    b.Navigation("AgentCalls");

                    b.Navigation("NPCs");

                    b.Navigation("Players");

                    b.Navigation("PlotReviews");

                    b.Navigation("PlotThreads");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Adnd.Server.Models.Player", b =>
                {
                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
