// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Adnd.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adnd.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607121640_EFRelationships")]
    partial class EFRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adnd.Server.Models.AgentCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("FromAgent")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Input")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<string>("OutputMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCallId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("ToAgent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCallId");

                    b.HasIndex("SessionId");

                    b.HasIndex("GameId", "Status", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("AgentCalls");
                });

            modelBuilder.Entity("Adnd.Server.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonElement>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonElement>("Conditions")
                        .HasColumnType("jsonb");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer");

                    b.Property<JsonElement>("CustomFields")
                        .HasColumnType("jsonb");

                    b.Property<JsonElement>("Inventory")
                        .HasColumnType("jsonb");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<JsonElement>("Skills")
                        .HasColumnType("jsonb");

                    b.Property<JsonElement>("Spells")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Adnd.Server.Models.CustomSystemDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("JsonDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("CustomSystems");
                });

            modelBuilder.Entity("Adnd.Server.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomSystemJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GameMasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameParameters")
                        .HasColumnType("text");

                    b.Property<string>("GameState")
                        .HasColumnType("text");

                    b.Property<string>("InviteCode")
                        .HasColumnType("text")
                        .HasColumnName("invitecode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlotSeed")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemVersion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GameMasterId");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasFilter("invitecode IS NOT NULL");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameState")
                        .HasColumnType("text");

                    b.Property<string>("PlotNodes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Adnd.Server.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Embedding")
                        .HasColumnType("vector");

                    b.Property<JsonElement>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WhisperFromId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhisperTarget")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId");

                    b.HasIndex("WhisperFromId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Adnd.Server.Models.NPC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonElement>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<JsonElement>("Inventory")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PlotThreadId")
                        .HasColumnType("uuid");

                    b.Property<JsonElement>("Skills")
                        .HasColumnType("jsonb");

                    b.Property<JsonElement>("Spells")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlotThreadId");

                    b.ToTable("NPCs");
                });

            modelBuilder.Entity("Adnd.Server.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanWhisper")
                        .HasColumnType("boolean");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("WhisperGroups")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Embedding")
                        .HasColumnType("vector");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("KeyEventMessageIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PlotThreads");
                });

            modelBuilder.Entity("Adnd.Server.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Adnd.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Adnd.Server.Models.Whisper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("TargetPlayerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Targets")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromPlayerId");

                    b.HasIndex("SessionId");

                    b.HasIndex("GameId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Whispers");
                });

            modelBuilder.Entity("Adnd.Server.Models.AgentCall", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("AgentCalls")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.AgentCall", "ParentCall")
                        .WithMany("ChildCalls")
                        .HasForeignKey("ParentCallId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Game");

                    b.Navigation("ParentCall");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Adnd.Server.Models.Character", b =>
                {
                    b.HasOne("Adnd.Server.Models.Player", "Player")
                        .WithOne("Character")
                        .HasForeignKey("Adnd.Server.Models.Character", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Adnd.Server.Models.CustomSystemDefinition", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.Game", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.User", "GameMaster")
                        .WithMany()
                        .HasForeignKey("GameMasterId");

                    b.Navigation("Creator");

                    b.Navigation("GameMaster");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameSession", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.Message", b =>
                {
                    b.HasOne("Adnd.Server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.Player", "WhisperFrom")
                        .WithMany()
                        .HasForeignKey("WhisperFromId");

                    b.Navigation("Player");

                    b.Navigation("Session");

                    b.Navigation("WhisperFrom");
                });

            modelBuilder.Entity("Adnd.Server.Models.NPC", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("NPCs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.PlotThread", "PlotThread")
                        .WithMany()
                        .HasForeignKey("PlotThreadId");

                    b.Navigation("Game");

                    b.Navigation("PlotThread");
                });

            modelBuilder.Entity("Adnd.Server.Models.Player", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.PlotThread", b =>
                {
                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany("PlotThreads")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Adnd.Server.Models.RefreshToken", b =>
                {
                    b.HasOne("Adnd.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adnd.Server.Models.Whisper", b =>
                {
                    b.HasOne("Adnd.Server.Models.Player", "FromPlayer")
                        .WithMany()
                        .HasForeignKey("FromPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adnd.Server.Models.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromPlayer");

                    b.Navigation("Game");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Adnd.Server.Models.AgentCall", b =>
                {
                    b.Navigation("ChildCalls");
                });

            modelBuilder.Entity("Adnd.Server.Models.Game", b =>
                {
                    b.Navigation("AgentCalls");

                    b.Navigation("NPCs");

                    b.Navigation("Players");

                    b.Navigation("PlotThreads");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Adnd.Server.Models.GameSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Adnd.Server.Models.Player", b =>
                {
                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
